# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.7.0'
    hooks:
      - id: autopep8
        args:
          - --recursive
          - --in-place
          - --aggressive
          - --aggressive
          - --hang-closing
          - --max-line-length=99

  - repo: https://github.com/PyCQA/isort
    rev: "5.10.1"
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        args:
          - --config
          - .flake8
        # The list of directories and files to check - matches flake8
        # configuration in setup.cfg, but has a slightly different
        # purpose. setup.cfg tells flake8 what to check when called e.g.
        # by pre-commit or IDE linter integration, the list below tells
        # *pre-commit* to which files to apply flake8 check.
        files: >
          (?x)^(
            bin/.*|
            examples/.*|
            tests/.*|
            tmt/.*|
            setup.py
          )$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.982"
    hooks:
      - id: mypy
        additional_dependencies: [types-click]
        pass_filenames: false
        args:
          - --config-file
          - mypy.ini

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.18.3"
    hooks:
      - id: check-metaschema
        name: "Check JSON schemas validity"
        files: ^tmt/schemas/.*\.yaml

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint
        files: ^tmt/schemas/.*\.yaml

  # Yet another static analysis - these hooks use regular expressions to
  # process Python code, and offer interesting "metalinters", checks for
  # what we do to appease flake8 and mypy linters.
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      # Enforce `noqa` and `type: ignore` to always appear with specific
      # error code(s).
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore

      # Other potentially useful hooks for future consideration:
      #
      # - id: python-check-mock-methods
      # - id: python-no-eval
      # - id: python-no-log-warn
      # - id: python-use-type-annotations
      # - id: text-unicode-replacement-char

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.215'
    hooks:
      - id: ruff
        # Respect `exclude` and `extend-exclude` settings.
        args:
          - "--config"
          - "ruff.toml"
        files: >
          (?x)^(
            bin/.*|
            examples/.*|
            tests/.*|
            tmt/.*|
            setup.py
          )$
